# Generated by Django 3.1.6 on 2021-02-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=20)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('autor', models.CharField(db_index=True, max_length=150)),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
